import { NextPage } from "next";
import Page from "../components/Page";
import {Typography} from "@material-ui/core";

const Index: NextPage = () => {
  return (
    <Page
      title="linkedin-redesign"
      description="Generated by Create Next Stack."
    >
      <Typography variant='h3'>HOme Page</Typography>
    </Page>
  );
};

export default Index;

