import { NextPage } from "next";
import Page from "../components/Page";
import {Text} from "@chakra-ui/react";

const Index: NextPage = () => {
  return (
    <Page
      title="linkedin-redesign"
      description="Generated by Create Next Stack."
    >
      <Text variant='h3'>HOme Page</Text>
    </Page>
  );
};

export default Index;

