import { NextPage } from "next";
import Page from "../components/Page";
import {Text} from "@chakra-ui/react";
import Layout from "../components/layout";
import TabNavigationBar from "../components/TabNavigationBar";
import HomePage from "../scenes/HomePage";
// import Layout from "../components/layout";

const Index = () => {
  return (
    <Page
      title="linkedin-redesign"
      description="Generated by Create Next Stack."
    >
        <TabNavigationBar links={[
            'Posts', 'Articles', 'Companies', 'Jobs'
        ]} />

        <HomePage/>

    </Page>
  );
};


export default Index;

